name: Nightly Python Job

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-python:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: nightly-output
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Hello World and save output
        run: |
          python main.py > output.txt
          echo "Created file:"
          cat output.txt

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: nightly-output
          path: output.txt
          retention-days: 7

  process-artifact:
    needs: run-python           # depends on run-python
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nightly-output
          path: ./downloaded_output

      - name: Show artifact content
        run: cat ./downloaded_output/output.txt
